name: Build release (master)
on:
  push:
    tags:
      - 'v*'
jobs:
  Prosjektoversikt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm packages
        run: |
          npm install
        working-directory: ./Prosjektoversikt/
      - name: Build SPFx
        run: |
          gulp default --ship
        working-directory: ./Prosjektoversikt/
      - name: Package SPFx
        run: |
          gulp package-solution --ship
        working-directory: ./Prosjektoversikt/
      - uses: actions/upload-artifact@v3
        with:
          name: Prosjektoversikt-release
          path:  |
            Prosjektoversikt/template.xml
            Prosjektoversikt/Install.ps1
            Prosjektoversikt/sharepoint/solution/pp-addons-prosjektoversikt.sppkg
      - uses: actions/upload-artifact@v3
        with:
          name: Prosjektoversikt-release
          path: Prosjektoversikt/sharepoint/solution/pp-addons-prosjektoversikt.sppkg

  
  UploadRelease:
    runs-on: ubuntu-latest
    needs: [Prosjektoversikt]
    env:
      SHA8: ${GITHUB_SHA::8}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      
      - name: ZIP release package
        uses: thedoctor0/zip-release@master
        with:
          filename: 'Prosjektoversikt-release.zip'
          path: Prosjektoversikt-release

      - name: (Prosjektoversikt) Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Prosjektoversikt-release.zip
          asset_name: Prosjektoversikt-$tag-release.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: ""